version: '3.6'
services:
  postgres:
    image: mdillon/postgis:11
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=testingwithrentals
    networks:
      - mynetwork
    ports:
      - "5434:5432"
    volumes:
      - ./sql-init.sql:/docker-entrypoint-initdb.d/sql-init.sql
  app:
    build:
      context: .
    networks:
      - mynetwork
    ports:
      - 8080:8080
networks:
  mynetwork:
    driver: bridge